apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: grzesiekoladele/client_app:v2
          ports:
            - containerPort: 8080
          env:
            - name: REST-TEMPLATE_SERVER_HOST
              value: server-cluster-ip-service
            - name: REST-TEMPLATE_MESSAGE_SERVICE_HOST
              value: message-service-cluster-ip-service