apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: grzesiekoladele/server_app:v1
          ports:
            - containerPort: 8181
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-cluster-ip-service:5432/kubernetes
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create-drop